# `dependabot.yml` file with
# customized schedule for version updates

version: 2
updates:
  # Keep npm dependencies up to date
  - package-ecosystem: "npm"
    directory: "/"
    # Check the npm registry on the 1st of every month at 14:00 NZ Time
    schedule:
      interval: "monthly"
      time: "14:00"
      timezone: "Pacific/Auckland"
    groups:
      dev-dependencies:
        patterns: 
          - "*"
